

### POST request to create a subscriber
POST http://localhost:8080/api/v1/suscribers
Content-Type: application/json

{ 
    "email": "ishwor.karki@example.com"
}

### Get request to get all suscribers
GET http://localhost:8080/api/v1/suscribers

### To register users
POST   http://localhost:8080/api/v1/users/register
Content-Type: application/json

{
    "username":"ishwor",
    "email":"iisssdsssssdssddsdf@gmail.com",
    "password":"1234"
}

### to login user
POST   http://localhost:8080/api/v1/users/login
Content-Type: application/json

{
    "email":"iisssdsssssdsddsdf@gmail.com",
    "password":"1234"
}

### to create products
POST  http://localhost:8080/api/v1/products
Content-Type: application/json

{
    "name":"rissoles",
    "description":"thi si s a rissoles ",
    "calorie":500,
    "price":400,
    "category":"rawChicken"

}

### to get all products
GET  http://localhost:8080/api/v1/products

### to update a product
PUT  http://localhost:8080/api/v1/products/67a32be8bad44687eb693dbe
Content-Type: application/json

{
    "name":"rissole",
    "description":"thi si s a rissoles ",
    "calorie":500,
    "price":400,
    "category":"rawChicken"

}


### to delete a product
DELETE  http://localhost:8080/api/v1/products/67a32be8bad44687eb693dbe



### to add item in a cart
POST  http://localhost:8080/api/v1/cart
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imlpc3NzZHNzc3NzZHNkZHNkZkBnbWFpbC5jb20iLCJpYXQiOjE3Mzg5OTk4NTgsImV4cCI6MTczOTA4NjI1OH0.BzKZqde5Mu2j536s8HeZ38ZHkayTCe5_PIhgZBFKqcE

{
    "productId":"6788cc8f9a56c45f3896ce09",
    "quantity":3
}

### to add item in a cart
PUT   http://localhost:8080/api/v1/cart
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imlpc3NzZHNzc3NzZHNkZHNkZkBnbWFpbC5jb20iLCJpYXQiOjE3Mzg5OTk4NTgsImV4cCI6MTczOTA4NjI1OH0.BzKZqde5Mu2j536s8HeZ38ZHkayTCe5_PIhgZBFKqcE

{
    "productId":"6788cc8f9a56c45f3896ce09",
    "quantity":2
}
